### ISSUE TITLE
calagator.org responds to HEAD requests with 404

### ISSUE THREAD

**Issue by edrex** [calagator/calagator.org#17]
```
> curl --head http://calagator.org/
HTTP/1.1 404 Not Found
Server: nginx/1.8.0
Date: Fri, 10 Jun 2016 00:11:57 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 881
Connection: keep-alive
X-Request-Id: 7c683c5d-f9e6-437b-bcea-4eb138f59561
X-Runtime: 0.002947
```

I found this while checking pdxruby.org for dead links, see https://github.com/pdxruby/pdxruby.github.io/issues/4#issuecomment-225059757.

@reidab

**Comment by aeschright** [comment]
Thanks for checking this! I don't know of a specific reason that we would want to update the behavior, but if you think of one, you could file another ticket.
