### ISSUE TITLE
New wave of spam

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator.org#18]
We're getting a lot of spam that's changing old events and venues to things like "http://buy-baclofen.eu/ - baclofen http://buy-suhagra.cricket/ - buy suhagra http://buyalbendazole.download/ - buy albendazole on line". Can someone have a look at the blacklist and see if there's terms we could add to handle this?

**Comment by jc00ke** [comment]
I just added a bunch in a3c656d1815f4bebb01cd8aecbc4e01eb6f67828.

Maybe it's time we integrate with some blacklisting API, or we pull down from a service like http://urlblacklist.com/?sec=download ?

**Comment by jc00ke** [comment]
More in fecfd4e

@aeschright can we get a deploy? Thanks!

**Comment by reidab** [comment]
@jc00ke `master` on calagator/calagator.org should by auto-deployed by Travis 💃 

https://travis-ci.org/calagator/calagator.org/builds/137598924

**Comment by jc00ke** [comment]
Very cool!

**Comment by jc00ke** [comment]
We're really playing cat-and-mouse here. I [reached out](https://twitter.com/jc00ke/status/748555674578149376) to LegitScript but they won't share their list. I found [this list](http://www.rxassist.org/pap-info/brand-drug-list-print) which is pretty good, but cursory testing shows it doesn't have some that we have, and vice versa.

More searching pulled up http://www.needymeds.org/brand-drug and http://www.disabled-world.com/medical/pharmaceutical/generic-equivalents.php which we could probably ETL into a giant list. I'd consider even making this an API on its own so others can hit it.

Also found [this FDA list](http://www.fda.gov/AboutFDA/CentersOffices/OfficeofMedicalProductsandTobacco/CDER/ucm126391.htm) which we'd have to pull out the names from the PDF :frowning:

**Comment by jc00ke** [comment]
I'd like to try [reCAPTCHA](https://www.google.com/recaptcha/intro/index.html), any objections?

**Comment by jc00ke** [comment]
I'm going to close this in favor of calagator/calagator#504
