### ISSUE TITLE
https for calagator.org

### ISSUE THREAD

**Issue by jc00ke** [calagator/calagator.org#19]
Options
- CloudFlare Universal SSL
- Let's Encrypt rotating cert
- permanent cert (who would buy?)

**Comment by aeschright** [comment]
I think we resolved this with Cloudflare. @reidab any details to add?

**Comment by reidab** [comment]
We're still running this through Cloudflare SSL, though we could switch to LE with the new server setup. We apparently hadn't turned on any SSL enforcement redirects when we originally set that up, so I just enabled those.
