### ISSUE TITLE
Importing from meetup.com ERROR

### ISSUE THREAD

**Issue by jonhannis** [calagator/calagator.org#27]
ERROR: Unable to import: Unknown error: 401 Unauthorized: {"details":"API requests must be key-signed, oauth-signed, or accompanied by a key: https:\/\/www.meetup.com\/meetup_api\/docs\/#authentication","code":"not_authorized","problem":"You are not authorized to make that request"}

**Comment by jonhannis** [comment]
did wework finally break meetup? If so, suggesting alternatives are appreciated

**Comment by aeschright** [comment]
Meetup appears to have deprecated the endpoint we use back in 2019. So to continue (resume?) importing events we'll need to implement the v3 GraphQL API.

**Comment by aeschright** [comment]
Closing as duplicate of https://github.com/calagator/calagator/issues/593
