### ISSUE TITLE
reCaptcha failing, preventing editing

### ISSUE THREAD

**Issue by jamesshore** [calagator/calagator.org#42]
reCaptcha is failing with the error "ERROR for site owner: Invalid domain for site key." This prevents entries from being edited, and presumably causes problems throughout the site. See attached screenshot.

Reproduced at http://calagator.stumptownsyndicate.org/events/1250476950/edit

<img width="367" alt="Screen Shot 2020-03-16 at 2 08 55 PM" src="https://user-images.githubusercontent.com/123129/76799993-e8af2c80-678f-11ea-9fdc-39836399c51f.png">

**Comment by jamesshore** [comment]
The underlying issue appears to be that events on calagator.org are linked to calagator.stumptownsyndicate.org. If I manually edit the above URL from `http://calagator.stumptownsyndicate.org/events/1250476950/edit` to `http://calagator.org/events/1250476950/edit`, it works.

**Comment by aeschright** [comment]
Thanks for filing an issue on this. It was fixed a while ago, but we forgot to make the update here. Let us know if you see anything else!
