### ISSUE TITLE
All links are resolving to localhost

### ISSUE THREAD

**Issue by turoczy** [calagator/calagator.org#53]
The links on the front page are resolving to localhost instead of calagator.org so they're all throwing 404s.

**Comment by evolve2k** [comment]
The main site is working for me.
@turoczy shout out if you're still getting this. 

Otherwise suggest close this out.
Recommend Close.

**Comment by aeschright** [comment]
I'm not sure why that was happening, but I'll close since it no longer seems to be the case.
