### ISSUE TITLE
calagator.org server error

### ISSUE THREAD

**Issue by sullis** [calagator/calagator.org#58]
I am trying to add an event to calagator.org

The web application is returning a generic server error

<img width="597" alt="image" src="https://user-images.githubusercontent.com/30938/150705707-ddd03905-703a-4c13-a213-52bedf12b5d5.png">

**Comment by aeschright** [comment]
I upgraded Solr (our search engine) last week and it seems to have broken things. I didn't want to put it off any longer because of the Log4j issue, but I should have checked that everything was running smoothly afterward. Thanks for your patience while I figure out how to fix this.

**Comment by aeschright** [comment]
You can post events again. We have to bail on the Solr upgrade for the time being because Sunspot (the gem that we use to connect to Solr) is still not updated for version 8.
